"""'Understand the system' pages: the system diagram and the chunk / embedding viewers,
embedded in the Streamlit app so everything can be demoed from one place.

The viewers are self-contained HTML files generated by scripts/ (they quote corpus text, so
they live in the gitignored data/ folder and are rebuilt with `make viz`). Each is its own
page, so a large viewer only loads when you open it.
"""

from pathlib import Path

import streamlit as st
import streamlit.components.v1 as components

from rag import config

DIAGRAM = config.ROOT / "assets" / "system_diagram.html"
CHUNK_VIEWER = config.PROCESSED_DIR / "chunk_viewer.html"
EMBEDDING_VIEWER = config.PROCESSED_DIR / "embedding_viewer.html"


@st.cache_data(show_spinner=False)
def _read(path: str, mtime: float) -> str:          # mtime in the key: a regenerated file is re-read
    return Path(path).read_text()


def _embed(path: Path, height: int, how_to_build: str) -> None:
    if not path.exists():
        st.info(f"This view hasn't been generated on this machine yet. Build it with:\n\n```bash\n{how_to_build}\n```")
        return
    components.html(_read(str(path), path.stat().st_mtime), height=height, scrolling=True)


def diagram_page() -> None:
    st.title("System diagram")
    st.caption("How the pieces fit: offline ingestion into Chroma, then the LangGraph flow that answers "
               "(or refuses) each question, with the LLM-only baseline alongside.")
    _embed(DIAGRAM, 1700, "(assets/system_diagram.html is part of the repo)")


def chunk_viewer_page() -> None:
    from lab.rag_lab import pipeline_header
    pipeline_header("chunks")
    st.caption("Every document's cleaned text, split into the exact chunks that were embedded. Pick a document "
               "on the left; colours are chunks, green is overlap. 'Chunks as embedded' shows the header each "
               "chunk carries. The first load takes a few seconds.")
    if config.PUBLIC_DEPLOYMENT:
        st.info("On this public site, full text is shown only for the openly licensed (CC BY-SA) Wikipedia "
                "articles. The other 36 documents (journal papers, reports, arXiv preprints) are searched and "
                "quoted in answers, but not republished here in full.", icon=":material/description:")
    _embed(CHUNK_VIEWER, 900, "uv run python scripts/visualize_chunks.py")
    from lab.learn import render_learning
    render_learning("chunks")
    from lab.nav import tour_footer
    tour_footer("chunks")


def embedding_viewer_page() -> None:
    from lab.rag_lab import pipeline_header
    pipeline_header("embeddings")
    from rag.bootstrap import chunk_count
    st.caption(f"All {chunk_count():,} chunk embeddings projected to 2D. Nearby dots mean similar meaning. Click a dot "
               "to see its 1,536 numbers and nearest neighbours, or pick a test question to watch retrieval "
               "draw lines to its top-5 chunks.")
    _embed(EMBEDDING_VIEWER, 900, "uv run python scripts/visualize_embeddings.py")
    from lab.learn import render_learning
    render_learning("embeddings")
    from lab.nav import tour_footer
    tour_footer("embeddings")
